# Generated by Django 5.2.17 on 2026-09-11 11:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RiderProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("full_name", models.CharField(max_length=150)),
                ("phone", models.CharField(max_length=20)),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True,
                        help_text="Optional - defaults to the account email if left blank.",
                        max_length=254,
                    ),
                ),
                (
                    "service_area",
                    models.CharField(
                        help_text="Area/zone this rider delivers in, e.g. 'Ibadan North, Oyo State'.",
                        max_length=150,
                    ),
                ),
                (
                    "vehicle_type",
                    models.CharField(
                        choices=[
                            ("bicycle", "Bicycle"),
                            ("motorcycle", "Motorcycle"),
                            ("car", "Car"),
                            ("van", "Van"),
                            ("on_foot", "On Foot"),
                        ],
                        default="motorcycle",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("suspended", "Suspended"),
                            ("inactive", "Inactive"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("rejection_reason", models.TextField(blank=True)),
                ("verified", models.BooleanField(default=False)),
                ("is_available", models.BooleanField(default=False)),
                ("bank_code", models.CharField(blank=True, max_length=10)),
                ("bank_name", models.CharField(blank=True, max_length=100)),
                ("bank_account_number", models.CharField(blank=True, max_length=20)),
                ("bank_account_name", models.CharField(blank=True, max_length=150)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rider_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rider_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Rider Profile",
                "verbose_name_plural": "Rider Profiles",
                "db_table": "rider_profiles",
            },
        ),
    ]
