# Generated by Django 6.1.1 on 2026-09-19 01:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0001_initial'),
        ('orders', '0006_refund_approved_at_refund_item_received_at_and_more'),
        ('riders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiderEarning',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Held'), ('available', 'Available'), ('paid', 'Withdrawn'), ('cancelled', 'Cancelled'), ('reversed', 'Reversed')], default='pending', max_length=20)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('delivery_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rider_earning', to='logistics.deliverytask')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rider_earnings', to='orders.order')),
                ('pickup_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rider_earning', to='logistics.pickuptask')),
                ('reversal_of', models.ForeignKey(blank=True, help_text='Set only on a reversal row - points back at the original earning it cancels out.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversals', to='riders.riderearning')),
                ('rider', models.ForeignKey(help_text="PROTECT, not SET_NULL/CASCADE - an earning must never lose track of who it's owed to.", on_delete=django.db.models.deletion.PROTECT, related_name='earnings', to='riders.riderprofile')),
            ],
            options={
                'db_table': 'rider_earnings',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['rider', 'status'], name='rider_earni_rider_i_95bb41_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('delivery_task__isnull', True), ('pickup_task__isnull', False)), models.Q(('delivery_task__isnull', False), ('pickup_task__isnull', True)), _connector='OR'), name='rider_earning_exactly_one_task'), models.UniqueConstraint(condition=models.Q(('pickup_task__isnull', False), ('reversal_of__isnull', True)), fields=('pickup_task',), name='unique_original_earning_per_pickup_task'), models.UniqueConstraint(condition=models.Q(('delivery_task__isnull', False), ('reversal_of__isnull', True)), fields=('delivery_task',), name='unique_original_earning_per_delivery_task')],
            },
        ),
    ]
