# Generated by Django 6.0.6 on 2026-07-12 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('shipping', 'Shipping'), ('local_delivery', 'Local Delivery')], default='shipping', help_text='Chosen at checkout; used to build the right tracking pipeline once payment succeeds (see apps.delivery).', max_length=20),
        ),
    ]
