# Generated by Django 6.0.6 on 2026-08-26 00:00
#
# Phase 4 - multi-seller product/order architecture.
#
# Adds seller ownership to the line item (not the Order, since one Order
# can contain products from several sellers), plus a frozen commission
# snapshot and a per-item fulfillment status that each seller advances
# independently of Order.status.
#
# All three fields are nullable/defaulted so this is safe to run against
# an existing (possibly non-empty) `orders_orderitem` table: existing rows
# simply get seller=NULL (treated as platform-owned, matching how
# catalog.Product.seller already defaults for pre-marketplace products),
# platform_commission_rate=NULL, and fulfillment_status='pending'. No
# backfill is required because every OrderItem so far was created before
# the marketplace existed, i.e. always against platform-owned products.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_delivery_method'),
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='seller',
            field=models.ForeignKey(blank=True, help_text='Null = this was a platform-owned product (no seller).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='sellers.sellerprofile'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='platform_commission_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='fulfillment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
