# Generated by Django 6.1.1 on 2026-09-19 01:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_refund'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='refund',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='refund',
            name='item_received_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='refund',
            name='reason_category',
            field=models.CharField(choices=[('not_as_described', 'Item not as described'), ('damaged', 'Arrived damaged'), ('wrong_item', 'Wrong item received'), ('not_delivered', 'Never arrived'), ('changed_mind', 'Changed my mind'), ('other', 'Other')], default='other', max_length=30),
        ),
        migrations.AddField(
            model_name='refund',
            name='seller_condition_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='refund',
            name='seller_condition_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='refund',
            name='reason',
            field=models.TextField(help_text="Buyer's explanation, in addition to reason_category."),
        ),
        migrations.AlterField(
            model_name='refund',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('under_review', 'Under Review'), ('return_in_progress', 'Return In Progress'), ('item_received', 'Item Received'), ('seller_condition_confirmed', 'Seller Condition Confirmed'), ('platform_approved', 'Platform Approved'), ('processing', 'Processing'), ('processed', 'Refunded'), ('rejected', 'Rejected'), ('failed', 'Failed')], default='requested', max_length=30),
        ),
        migrations.CreateModel(
            name='RefundEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('file', models.FileField(upload_to='refund_evidence/%Y/%m/')),
                ('refund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='orders.refund')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'refund_evidence',
                'ordering': ['created_at'],
            },
        ),
    ]
