# Generated by Django 6.0.8 on 2026-09-19 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0008_merge_0006_refund_and_0007_orderitem_delivered_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitem",
            name="delivered_at",
        ),
    ]
