# Generated by Django 6.1 on 2026-08-25 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CUSTOMER', 'Customer'), ('ADMIN', 'Administrator'), ('STAFF', 'Staff'), ('SELLER', 'Seller'), ('AFFILIATE', 'Affiliate')], default='CUSTOMER', max_length=20),
        ),
    ]
