# Generated by Django 6.0.8 on 2026-09-16 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("CUSTOMER", "Customer"),
                    ("ADMIN", "Administrator"),
                    ("STAFF", "Staff"),
                    ("SELLER", "Seller"),
                    ("AFFILIATE", "Affiliate"),
                    ("RIDER", "Delivery Rider"),
                ],
                default="CUSTOMER",
                max_length=20,
            ),
        ),
    ]
