# Generated by Django 5.2.17 on 2026-09-01 05:17

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_order_affiliate_order_affiliate_code"),
        ("sellers", "0002_sellerprofile_affiliate_commission_rate"),
    ]

    operations = [
        migrations.CreateModel(
            name="SellerEarning",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "order_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Gross line-item amount (OrderItem.subtotal) this earning was calculated from.",
                        max_digits=12,
                    ),
                ),
                (
                    "platform_commission_rate",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "platform_commission_amount",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "affiliate_commission_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="What was paid out to an affiliate on this same line item, if any - shown for transparency; this amount already came out of the seller's share, not the platform's (spec section 17).",
                        max_digits=12,
                    ),
                ),
                (
                    "earning_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="What the seller actually nets: order_amount - platform_commission_amount - affiliate_commission_amount.",
                        max_digits=12,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("available", "Available"),
                            ("paid", "Paid"),
                            ("cancelled", "Cancelled"),
                            ("reversed", "Reversed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=255)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="seller_earnings",
                        to="orders.order",
                    ),
                ),
                (
                    "order_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="seller_earnings",
                        to="orders.orderitem",
                    ),
                ),
                (
                    "reversal_of",
                    models.ForeignKey(
                        blank=True,
                        help_text="Set only on a reversal row - points back at the original earning it cancels out.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reversals",
                        to="sellers.sellerearning",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        help_text="PROTECT, not SET_NULL/CASCADE - an earning must never lose track of who it's owed to.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="earnings",
                        to="sellers.sellerprofile",
                    ),
                ),
            ],
            options={
                "db_table": "seller_earnings",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["seller", "status"],
                        name="seller_earn_seller__595663_idx",
                    ),
                    models.Index(
                        fields=["order", "status"],
                        name="seller_earn_order_i_7d1237_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("reversal_of__isnull", True)),
                        fields=("order_item",),
                        name="unique_original_earning_per_order_item",
                    )
                ],
            },
        ),
    ]
