# Generated by Django 5.2.17 on 2026-09-04 04:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sellers", "0003_sellerearning"),
    ]

    operations = [
        migrations.CreateModel(
            name="SellerPayout",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="The exact sum of the SellerEarning rows this payout reserved.",
                        max_digits=12,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("paid", "Paid"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("reference", models.CharField(max_length=100, unique=True)),
                ("bank_name", models.CharField(max_length=100)),
                ("bank_account_number", models.CharField(max_length=20)),
                ("bank_account_name", models.CharField(max_length=150)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.CharField(blank=True, max_length=255)),
                (
                    "seller",
                    models.ForeignKey(
                        help_text="PROTECT - a payout must never lose track of who requested it.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payouts",
                        to="sellers.sellerprofile",
                    ),
                ),
            ],
            options={
                "db_table": "seller_payouts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="sellerearning",
            name="payout",
            field=models.ForeignKey(
                blank=True,
                help_text="Set once this earning has been reserved by a payout request (Phase 9) - null means it's still unreserved AVAILABLE balance the seller could request.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="earnings",
                to="sellers.sellerpayout",
            ),
        ),
        migrations.AddIndex(
            model_name="sellerpayout",
            index=models.Index(
                fields=["seller", "status"], name="seller_payo_seller__63d840_idx"
            ),
        ),
    ]
