# Generated by Django 6.0.1 on 2026-09-05 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0002_payout'),
        ('sellers', '0003_sellerearning'),
    ]

    operations = [
    ]
