# Generated by Django 5.2.17 on 2026-09-04 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sellers", "0004_sellerpayout_sellerearning_payout_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sellerprofile",
            name="bank_code",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="sellerprofile",
            name="provider_reference",
            field=models.CharField(
                blank=True,
                help_text="Paystack's transfer_code for this payout, once sent (Phase 10).",
                max_length=100,
            ),
        ),
    ]
