# Generated by Django 6.0.1 on 2026-09-05 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0004_merge_0002_payout_0003_sellerearning'),
        ('sellers', '0005_sellerprofile_bank_code_and_more'),
    ]

    operations = [
    ]
