# Generated by Django 5.2.17 on 2026-09-06 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sellers", "0006_merge_20260905_2212"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Payout",
        ),
    ]
