# Generated by Django 6.1.1 on 2026-09-19 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0007_delete_payout'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerearning',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, help_text="Set the moment this earning enters Held (CONFIRMED) - spec section 22's hold countdown is measured from here.", null=True),
        ),
        migrations.AlterField(
            model_name='sellerearning',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Held'), ('available', 'Available'), ('paid', 'Withdrawn'), ('cancelled', 'Cancelled'), ('reversed', 'Reversed')], default='pending', max_length=20),
        ),
    ]
