# Generated by Django 5.2.17 on 2026-08-29 06:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("affiliates", "0001_initial"),
        ("catalog", "0002_product_commission_rate_product_seller"),
    ]

    operations = [
        migrations.CreateModel(
            name="AffiliateLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("referral_code", models.CharField(editable=False, max_length=20)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "affiliate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="affiliates.affiliateprofile",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="affiliate_links",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "db_table": "affiliate_links",
                "ordering": ["-created_at"],
                "unique_together": {("affiliate", "product")},
            },
        ),
        migrations.CreateModel(
            name="AffiliateClick",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "session_key",
                    models.CharField(
                        blank=True,
                        help_text="Django session key of the visitor, used only to de-duplicate repeat clicks - not to identify a person.",
                        max_length=40,
                    ),
                ),
                (
                    "converted",
                    models.BooleanField(
                        default=False,
                        help_text="Set True in a later phase once this click leads to a paid, attributed order.",
                    ),
                ),
                (
                    "affiliate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="clicks",
                        to="affiliates.affiliateprofile",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="affiliate_clicks",
                        to="catalog.product",
                    ),
                ),
                (
                    "affiliate_link",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="clicks",
                        to="affiliates.affiliatelink",
                    ),
                ),
            ],
            options={
                "db_table": "affiliate_clicks",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["affiliate", "created_at"],
                        name="affiliate_c_affilia_a066de_idx",
                    ),
                    models.Index(
                        fields=["session_key", "product", "created_at"],
                        name="affiliate_c_session_b724d6_idx",
                    ),
                ],
            },
        ),
    ]
