# Generated by Django 5.2.17 on 2026-09-04 04:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("affiliates", "0003_affiliatecommission"),
    ]

    operations = [
        migrations.CreateModel(
            name="AffiliatePayout",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="The exact sum of the AffiliateCommission rows this payout reserved.",
                        max_digits=12,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("paid", "Paid"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("reference", models.CharField(max_length=100, unique=True)),
                ("bank_name", models.CharField(max_length=100)),
                ("bank_account_number", models.CharField(max_length=20)),
                ("bank_account_name", models.CharField(max_length=150)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "db_table": "affiliate_payouts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.RenameIndex(
            model_name="affiliatecommission",
            new_name="affiliate_c_affilia_dfeb5f_idx",
            old_name="affiliate_c_affilia_1f1f0a_idx",
        ),
        migrations.RenameIndex(
            model_name="affiliatecommission",
            new_name="affiliate_c_order_i_414a64_idx",
            old_name="affiliate_c_order_i_5c9d3e_idx",
        ),
        migrations.AlterField(
            model_name="affiliatecommission",
            name="affiliate_link",
            field=models.ForeignKey(
                blank=True,
                help_text="The link this conversion is credited through, if the affiliate had generated one for this exact product. Null doesn't invalidate the commission - attribution is by affiliate code, not by a specific link.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="commissions",
                to="affiliates.affiliatelink",
            ),
        ),
        migrations.AddField(
            model_name="affiliatepayout",
            name="affiliate",
            field=models.ForeignKey(
                help_text="PROTECT - a payout must never lose track of who requested it.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payouts",
                to="affiliates.affiliateprofile",
            ),
        ),
        migrations.AddField(
            model_name="affiliatecommission",
            name="payout",
            field=models.ForeignKey(
                blank=True,
                help_text="Set once this commission has been reserved by a payout request (Phase 9) - null means it's still unreserved AVAILABLE balance the affiliate could request.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="commissions",
                to="affiliates.affiliatepayout",
            ),
        ),
        migrations.AddIndex(
            model_name="affiliatepayout",
            index=models.Index(
                fields=["affiliate", "status"], name="affiliate_p_affilia_6ce7ab_idx"
            ),
        ),
    ]
