# Generated by Django 6.0.1 on 2026-09-05 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('affiliates', '0004_merge_affiliatecommission_affiliatepayout'),
        ('affiliates', '0005_affiliatepayout_bank_code_and_more'),
    ]

    operations = [
    ]
