# Generated by Django 6.1.1 on 2026-09-16 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliates', '0006_merge_20260905_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliateprofile',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='Optional - defaults to the account email if left blank.', max_length=254),
        ),
        migrations.AddField(
            model_name='affiliateprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='affiliateprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='affiliateprofile',
            name='promotional_channels',
            field=models.TextField(blank=True, help_text='Where this affiliate plans to promote products - blog, Instagram, YouTube, newsletter, etc.'),
        ),
    ]
