# Generated by Django 6.0.1 on 2026-06-16 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='purchase_completed',
            field=models.BooleanField(default=False),
        ),
    ]
