# Generated by Django 5.2.17 on 2026-09-13 20:34

import apps.logistics.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("delivery", "0001_initial"),
        ("orders", "0005_refund"),
        ("riders", "0001_initial"),
        ("sellers", "0007_delete_payout"),
    ]

    operations = [
        migrations.CreateModel(
            name="Package",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "reference",
                    models.CharField(
                        default=apps.logistics.models._package_reference,
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("ready", "Ready for Pickup"),
                            ("collected", "Collected"),
                            ("in_transit", "In Transit"),
                            ("delivered", "Delivered"),
                            ("exception", "Exception"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "weight_kg",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
            ],
            options={
                "db_table": "logistics_packages",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CollectionBatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("assigned", "Assigned to Rider"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("assigned_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.CharField(blank=True, max_length=255)),
                (
                    "rider",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="collection_batches",
                        to="riders.riderprofile",
                    ),
                ),
            ],
            options={
                "db_table": "logistics_collection_batches",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DeliveryTask",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("assigned", "Assigned"),
                            ("en_route", "En Route"),
                            ("delivered", "Delivered"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("failure_reason", models.CharField(blank=True, max_length=255)),
                (
                    "batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="delivery_tasks",
                        to="logistics.collectionbatch",
                    ),
                ),
                (
                    "delivery",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_task",
                        to="delivery.delivery",
                    ),
                ),
                (
                    "rider",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="delivery_tasks",
                        to="riders.riderprofile",
                    ),
                ),
                (
                    "packages",
                    models.ManyToManyField(
                        blank=True,
                        related_name="delivery_tasks",
                        to="logistics.package",
                    ),
                ),
            ],
            options={
                "db_table": "logistics_delivery_tasks",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PackageItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "order_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="package_items",
                        to="orders.orderitem",
                    ),
                ),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="package_items",
                        to="logistics.package",
                    ),
                ),
            ],
            options={
                "db_table": "logistics_package_items",
            },
        ),
        migrations.AddField(
            model_name="package",
            name="items",
            field=models.ManyToManyField(
                related_name="packages",
                through="logistics.PackageItem",
                to="orders.orderitem",
            ),
        ),
        migrations.CreateModel(
            name="PickupTask",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("assigned", "Assigned"),
                            ("en_route", "Rider En Route"),
                            ("collected", "Collected"),
                            ("not_ready", "Seller Not Ready"),
                            ("missing", "Package Missing"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("pickup_address", models.CharField(blank=True, max_length=255)),
                ("pickup_contact_phone", models.CharField(blank=True, max_length=20)),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("collected_at", models.DateTimeField(blank=True, null=True)),
                ("exception_reason", models.CharField(blank=True, max_length=255)),
                (
                    "batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pickup_tasks",
                        to="logistics.collectionbatch",
                    ),
                ),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pickup_tasks",
                        to="logistics.package",
                    ),
                ),
                (
                    "rider",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pickup_tasks",
                        to="riders.riderprofile",
                    ),
                ),
            ],
            options={
                "db_table": "logistics_pickup_tasks",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RiderAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("object_id", models.UUIDField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("offered", "Offered"),
                            ("accepted", "Accepted"),
                            ("declined", "Declined"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="offered",
                        max_length=20,
                    ),
                ),
                ("offered_at", models.DateTimeField(auto_now_add=True)),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.CharField(blank=True, max_length=255)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "rider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="riders.riderprofile",
                    ),
                ),
            ],
            options={
                "db_table": "logistics_rider_assignments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RouteActivity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("sequence", models.PositiveIntegerField()),
                (
                    "activity_type",
                    models.CharField(
                        choices=[("pickup", "Pickup"), ("delivery", "Delivery")],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("arrived", "Arrived"),
                            ("completed", "Completed"),
                            ("skipped", "Skipped"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("arrived_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="route_activities",
                        to="logistics.collectionbatch",
                    ),
                ),
                (
                    "delivery_task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="route_activities",
                        to="logistics.deliverytask",
                    ),
                ),
                (
                    "pickup_task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="route_activities",
                        to="logistics.pickuptask",
                    ),
                ),
            ],
            options={
                "db_table": "logistics_route_activities",
                "ordering": ["batch", "sequence"],
            },
        ),
        migrations.CreateModel(
            name="SellerFulfillment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("ready_for_pickup", "Ready for Pickup"),
                            ("picked_up", "Picked Up"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("ready_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.CharField(blank=True, max_length=255)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seller_fulfillments",
                        to="orders.order",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fulfillments",
                        to="sellers.sellerprofile",
                    ),
                ),
            ],
            options={
                "db_table": "seller_fulfillments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="package",
            name="fulfillment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="packages",
                to="logistics.sellerfulfillment",
            ),
        ),
        migrations.AddConstraint(
            model_name="packageitem",
            constraint=models.UniqueConstraint(
                fields=("package", "order_item"), name="unique_package_order_item"
            ),
        ),
        migrations.AddIndex(
            model_name="riderassignment",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="logistics_r_content_8dcc96_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="routeactivity",
            constraint=models.UniqueConstraint(
                fields=("batch", "sequence"), name="unique_batch_sequence"
            ),
        ),
        migrations.AddConstraint(
            model_name="sellerfulfillment",
            constraint=models.UniqueConstraint(
                fields=("order", "seller"), name="unique_order_seller_fulfillment"
            ),
        ),
    ]
