# Generated by Django 5.2.17 on 2026-09-01 05:17

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0004_order_affiliate_order_affiliate_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="LedgerEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "entry_type",
                    models.CharField(
                        choices=[("sale", "Sale"), ("refund", "Refund")],
                        default="sale",
                        max_length=10,
                    ),
                ),
                ("gross_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "platform_commission_amount",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "seller_earning_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "affiliate_commission_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "payment_processing_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Paystack's own transaction fee, if/when that figure is captured from the provider response. Zero for now - no fee data is currently read from Paystack's verify/webhook payload; this field exists so that can be wired in later without a schema change.",
                        max_digits=12,
                    ),
                ),
                (
                    "refund_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Non-zero only on a REFUND row.",
                        max_digits=12,
                    ),
                ),
                (
                    "net_payable_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="What this row sends out of the platform's own pocket to external parties: seller_earning_amount + affiliate_commission_amount. Negative on a REFUND row.",
                        max_digits=12,
                    ),
                ),
                ("currency", models.CharField(default="NGN", max_length=3)),
                (
                    "reference",
                    models.CharField(
                        help_text="The order's reference - not unique on its own, since one order produces several rows (one per item, plus any refund rows).",
                        max_length=100,
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=255)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ledger_entries",
                        to="orders.order",
                    ),
                ),
                (
                    "order_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ledger_entries",
                        to="orders.orderitem",
                    ),
                ),
                (
                    "related_entry",
                    models.ForeignKey(
                        blank=True,
                        help_text="Set only on a REFUND row - points back at the original SALE row it partially or fully reverses.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="refund_entries",
                        to="ledger.ledgerentry",
                    ),
                ),
            ],
            options={
                "db_table": "ledger_entries",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["order", "entry_type"],
                        name="ledger_entr_order_i_bc752f_idx",
                    ),
                    models.Index(
                        fields=["reference"], name="ledger_entr_referen_4aa8d4_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("entry_type", "sale")),
                        fields=("order_item",),
                        name="unique_sale_entry_per_order_item",
                    )
                ],
            },
        ),
    ]
