# Generated by Django 6.1 on 2026-08-25 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='commission_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(blank=True, help_text='Null = platform-owned product (100% of the sale goes to the platform, no seller earnings are created).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='sellers.sellerprofile'),
        ),
    ]
