# Generated by Django 6.0.1 on 2026-09-05 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_product_affiliate_commission_rate'),
        ('catalog', '0004_review'),
    ]

    operations = [
    ]
