# Generated by Django 5.2.17 on 2026-09-11 10:26

import apps.core.fields
import apps.kyc.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("affiliates", "0006_merge_20260905_2212"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("riders", "__first__"),
        # ("accounts", "0001_initial")
        ("sellers", "0007_delete_payout"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AffiliateKYC",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_submitted", "Not Submitted"),
                            ("submitted", "Submitted"),
                            ("under_review", "Under Review"),
                            ("confirmed", "Confirmed"),
                            ("rejected", "Rejected"),
                            ("resubmission", "Resubmission Required"),
                        ],
                        default="not_submitted",
                        max_length=20,
                    ),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True)),
                ("display_name", models.CharField(blank=True, max_length=150)),
                (
                    "business_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("individual", "Individual / Sole Proprietor"),
                            ("registered_business", "Registered Business"),
                            ("company", "Limited Company"),
                        ],
                        max_length=30,
                    ),
                ),
                ("address_line", models.CharField(blank=True, max_length=255)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("state", models.CharField(blank=True, max_length=100)),
                (
                    "country",
                    models.CharField(blank=True, default="Nigeria", max_length=100),
                ),
                ("contact_phone", models.CharField(blank=True, max_length=20)),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                (
                    "id_document_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("nin", "National ID Number (NIN)"),
                            ("passport", "International Passport"),
                            ("drivers_license", "Driver's Licence"),
                            ("voters_card", "Voter's Card"),
                            ("cac_certificate", "CAC Certificate (Business)"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "id_document_number",
                    apps.core.fields.EncryptedCharField(blank=True, max_length=64),
                ),
                (
                    "id_document_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=apps.kyc.models._affiliate_kyc_document_path,
                    ),
                ),
                (
                    "affiliate",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kyc",
                        to="affiliates.affiliateprofile",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Affiliate KYC",
                "verbose_name_plural": "Affiliate KYC Records",
                "db_table": "affiliate_kyc",
            },
        ),
        migrations.CreateModel(
            name="BuyerKYC",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_submitted", "Not Submitted"),
                            ("submitted", "Submitted"),
                            ("under_review", "Under Review"),
                            ("confirmed", "Confirmed"),
                            ("rejected", "Rejected"),
                            ("resubmission", "Resubmission Required"),
                        ],
                        default="not_submitted",
                        max_length=20,
                    ),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True)),
                ("full_name", models.CharField(blank=True, max_length=150)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("address_line", models.CharField(blank=True, max_length=255)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("state", models.CharField(blank=True, max_length=100)),
                (
                    "country",
                    models.CharField(blank=True, default="Nigeria", max_length=100),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kyc",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Buyer KYC",
                "verbose_name_plural": "Buyer KYC Records",
                "db_table": "buyer_kyc",
            },
        ),
        migrations.CreateModel(
            name="RiderKYC",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_submitted", "Not Submitted"),
                            ("submitted", "Submitted"),
                            ("under_review", "Under Review"),
                            ("confirmed", "Confirmed"),
                            ("rejected", "Rejected"),
                            ("resubmission", "Resubmission Required"),
                        ],
                        default="not_submitted",
                        max_length=20,
                    ),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("operating_location", models.CharField(blank=True, max_length=150)),
                (
                    "emergency_contact_name",
                    models.CharField(blank=True, max_length=150),
                ),
                (
                    "emergency_contact_phone",
                    models.CharField(blank=True, max_length=20),
                ),
                (
                    "id_document_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("nin", "National ID Number (NIN)"),
                            ("passport", "International Passport"),
                            ("drivers_license", "Driver's Licence"),
                            ("voters_card", "Voter's Card"),
                            ("cac_certificate", "CAC Certificate (Business)"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "id_document_number",
                    apps.core.fields.EncryptedCharField(blank=True, max_length=64),
                ),
                (
                    "id_document_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=apps.kyc.models._rider_kyc_document_path,
                    ),
                ),
                (
                    "drivers_license_number",
                    apps.core.fields.EncryptedCharField(blank=True, max_length=64),
                ),
                ("drivers_license_expiry", models.DateField(blank=True, null=True)),
                (
                    "drivers_license_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=apps.kyc.models._rider_kyc_license_path,
                    ),
                ),
                ("vehicle_make", models.CharField(blank=True, max_length=100)),
                ("vehicle_model", models.CharField(blank=True, max_length=100)),
                ("vehicle_color", models.CharField(blank=True, max_length=50)),
                ("plate_number", models.CharField(blank=True, max_length=20)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rider",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kyc",
                        to="riders.riderprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rider KYC",
                "verbose_name_plural": "Rider KYC Records",
                "db_table": "rider_kyc",
            },
        ),
        migrations.CreateModel(
            name="SellerKYC",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_submitted", "Not Submitted"),
                            ("submitted", "Submitted"),
                            ("under_review", "Under Review"),
                            ("confirmed", "Confirmed"),
                            ("rejected", "Rejected"),
                            ("resubmission", "Resubmission Required"),
                        ],
                        default="not_submitted",
                        max_length=20,
                    ),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True)),
                (
                    "business_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("individual", "Individual / Sole Proprietor"),
                            ("registered_business", "Registered Business"),
                            ("company", "Limited Company"),
                        ],
                        max_length=30,
                    ),
                ),
                ("business_category", models.CharField(blank=True, max_length=100)),
                ("business_address_line", models.CharField(blank=True, max_length=255)),
                ("business_city", models.CharField(blank=True, max_length=100)),
                ("business_state", models.CharField(blank=True, max_length=100)),
                (
                    "business_country",
                    models.CharField(blank=True, default="Nigeria", max_length=100),
                ),
                ("contact_phone", models.CharField(blank=True, max_length=20)),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                (
                    "id_document_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("nin", "National ID Number (NIN)"),
                            ("passport", "International Passport"),
                            ("drivers_license", "Driver's Licence"),
                            ("voters_card", "Voter's Card"),
                            ("cac_certificate", "CAC Certificate (Business)"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "id_document_number",
                    apps.core.fields.EncryptedCharField(blank=True, max_length=64),
                ),
                (
                    "id_document_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=apps.kyc.models._seller_kyc_document_path,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "seller",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kyc",
                        to="sellers.sellerprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Seller KYC",
                "verbose_name_plural": "Seller KYC Records",
                "db_table": "seller_kyc",
            },
        ),
        migrations.CreateModel(
            name="KYCAuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("object_id", models.UUIDField()),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("submitted", "Submitted"),
                            ("under_review", "Moved Under Review"),
                            ("confirmed", "Confirmed"),
                            ("rejected", "Rejected"),
                            ("accessed", "Sensitive Field Accessed"),
                        ],
                        max_length=20,
                    ),
                ),
                ("from_status", models.CharField(blank=True, max_length=20)),
                ("to_status", models.CharField(blank=True, max_length=20)),
                ("notes", models.TextField(blank=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="kyc_audit_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "db_table": "kyc_audit_logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="kyc_audit_l_content_250d3c_idx",
                    )
                ],
            },
        ),
    ]
