# Generated by Django 5.2.17 on 2026-09-06 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="notification",
            new_name="notificatio_user_id_8a7c6b_idx",
            old_name="notifications_user_read_idx",
        ),
        migrations.AlterField(
            model_name="notification",
            name="url",
            field=models.CharField(
                blank=True,
                help_text="Where clicking this notification should take the user, if anywhere.",
                max_length=255,
            ),
        ),
    ]
